services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  db:
    container_name: db-dev
    image: postgres:17-alpine
    env_file:
      - .env.development
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    volumes:
      - "./backend:/app"
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_db: {}
